### ISSUE TITLE
Connaissance > import BDC > Versionning historique

### ISSUE THREAD

**Issue by linnataing** [fabnumdef/fabrique-chatbot-back#59]
Dans le cas d'un import, j'ai bien la confirmation d'import de mon nouveau fichier, mais je n'ai pas l'apparition de la nouvelle version de ma BDC dans l'historique.

Est-ce un bug ? ou c'est juste que ca prend du temps à être généré ? ou qu'il faut que je mette à jour la BDD pour que ca se mette à jour ?
https://www.loom.com/share/ba37a356fb0c465592dbc8f19d315b25

**Comment by vincentlaine** [comment]
Le versioning est crée à chaque fois qu'on met à jour le chatbot. Pour avoir une vision de chaque évol. A voir si on le précise dans le BO ou dans le gitbook.
